language: java
jdk: openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
install:
- mvn dependency:purge-local-repository -DmanualInclude="uk.ac.sussex.gdsc:gdsc-ij-parent,uk.ac.sussex.gdsc:gdsc-core"
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
